import type { ProviderOperation,OperationResult } from "@swasthyasetu/contracts/connectivity";
import { api } from "./api.ts";

export type ConnectivityState="OFFLINE"|"LIMITED"|"ONLINE";
interface StoredOperation{id:string;iv:number[];cipher:ArrayBuffer;payloadHash:string;actorId:string;facilityId:string;attempts:number;nextAttemptAt:number;status:"PENDING"|"REJECTED";error:string|null;createdAt:string}
const DB="swasthyasetu-provider-connectivity",OPS="operations",KEYS="keys",REFERENCE="diagnostic-reference";
function open():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,2);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(OPS))request.result.createObjectStore(OPS,{keyPath:"id"});if(!request.result.objectStoreNames.contains(KEYS))request.result.createObjectStore(KEYS);if(!request.result.objectStoreNames.contains(REFERENCE))request.result.createObjectStore(REFERENCE,{keyPath:"serviceId"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function key():Promise<CryptoKey>{const db=await open();const existing=await new Promise<CryptoKey|undefined>((resolve,reject)=>{const r=db.transaction(KEYS).objectStore(KEYS).get("device");r.onsuccess=()=>resolve(r.result as CryptoKey|undefined);r.onerror=()=>reject(r.error);});if(existing)return existing;const created=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);await new Promise<void>((resolve,reject)=>{const tx=db.transaction(KEYS,"readwrite");tx.objectStore(KEYS).put(created,"device");tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});return created;}
async function encrypt(value:unknown):Promise<{iv:number[];cipher:ArrayBuffer}>{const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(),new TextEncoder().encode(JSON.stringify(value)));return{iv:[...iv],cipher};}
async function decrypt(row:StoredOperation):Promise<ProviderOperation>{const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(row.iv)},await key(),row.cipher);return JSON.parse(new TextDecoder().decode(plain)) as ProviderOperation;}
function canonical(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`;}
async function digest(value:unknown):Promise<string>{const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(value)));return[...new Uint8Array(bytes)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
export async function queueProviderOperation(operation:ProviderOperation,scope:{actorId:string;facilityId:string}):Promise<void>{if(!globalThis.crypto?.subtle||!globalThis.indexedDB)throw new Error("Secure browser storage is unavailable; offline clinical writes are disabled.");const encrypted=await encrypt(operation),payloadHash=await digest(operation);const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(OPS,"readwrite");tx.objectStore(OPS).add({id:operation.operationId,...encrypted,payloadHash,actorId:scope.actorId,facilityId:scope.facilityId,attempts:0,nextAttemptAt:0,status:"PENDING",error:null,createdAt:operation.clientCreatedAt} satisfies StoredOperation);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
async function rows():Promise<StoredOperation[]>{const db=await open();return new Promise((resolve,reject)=>{const r=db.transaction(OPS).objectStore(OPS).getAll();r.onsuccess=()=>resolve(r.result as StoredOperation[]);r.onerror=()=>reject(r.error);});}
export async function queueCounts():Promise<{pending:number;rejected:number}>{const all=await rows();return{pending:all.filter(row=>row.status==="PENDING").length,rejected:all.filter(row=>row.status==="REJECTED").length};}
export async function syncProviderQueue(token:string):Promise<{sent:number;rejected:number}>{if(!navigator.onLine)return{sent:0,rejected:0};const now=Date.now();const candidates=(await rows()).filter(row=>row.status==="PENDING"&&row.nextAttemptAt<=now).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).slice(0,50);if(candidates.length===0)return{sent:0,rejected:0};const operations:ProviderOperation[]=[];const usable:StoredOperation[]=[];let bytes=0;for(const row of candidates){try{const operation=await decrypt(row);const size=new TextEncoder().encode(JSON.stringify(operation)).byteLength;if(bytes+size>512*1024)break;bytes+=size;operations.push(operation);usable.push(row);}catch{await mark(row,"REJECTED","Encrypted operation cannot be decrypted.");}}
 if(operations.length===0)return{sent:0,rejected:0};try{const response=await api<{results:OperationResult[]}>("/provider/sync/push",{method:"POST",body:JSON.stringify({operations})},token);for(const result of response.results){const row=usable.find(item=>item.id===result.operationId);if(!row)continue;if(result.status==="APPLIED"||result.status==="DUPLICATE")await remove(row.id);else await mark(row,"REJECTED",result.message??result.status);}return{sent:response.results.filter(r=>r.status==="APPLIED"||r.status==="DUPLICATE").length,rejected:response.results.filter(r=>r.status==="REJECTED"||r.status==="CONFLICT").length};}catch(error){for(const row of usable){row.attempts+=1;row.nextAttemptAt=Date.now()+Math.min(2**row.attempts*5000,900000)*(1+Math.random()*.2);row.error=error instanceof Error?error.message:"Sync failed";await put(row);}throw error;}}
async function put(row:StoredOperation):Promise<void>{const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(OPS,"readwrite");tx.objectStore(OPS).put(row);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
async function mark(row:StoredOperation,status:"REJECTED",error:string):Promise<void>{row.status=status;row.error=error;await put(row);}
async function remove(id:string):Promise<void>{const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(OPS,"readwrite");tx.objectStore(OPS).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
export async function purgeProviderConnectivity():Promise<void>{const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction([OPS,KEYS],"readwrite");tx.objectStore(OPS).clear();tx.objectStore(KEYS).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
export async function cacheDiagnosticReference(items:Array<{serviceId:string;districtCode:string;test:{code:string}}>):Promise<void>{const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(REFERENCE,"readwrite");for(const item of items)tx.objectStore(REFERENCE).put({...item,cachedAt:new Date().toISOString()});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
export async function cachedDiagnosticReference<T>(code:string,districtCode:string):Promise<T[]>{const db=await open();const values=await new Promise<unknown[]>((resolve,reject)=>{const request=db.transaction(REFERENCE).objectStore(REFERENCE).getAll();request.onsuccess=()=>resolve(request.result as unknown[]);request.onerror=()=>reject(request.error);});return values.filter((value):value is T&{districtCode:string;test:{code:string}}=>typeof value==="object"&&value!==null&&"districtCode"in value&&"test"in value&&(value as{districtCode:unknown}).districtCode===districtCode&&typeof(value as{test?:{code?:unknown}}).test?.code==="string"&&(value as{test:{code:string}}).test.code.toUpperCase()===code.toUpperCase()).map(value=>value as T);}
export async function connectivityState(apiBase=import.meta.env.VITE_API_URL??"http://localhost:4000"):Promise<ConnectivityState>{if(!navigator.onLine)return"OFFLINE";const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),3500);const started=performance.now();try{const response=await fetch(`${apiBase}/health`,{signal:controller.signal});return response.ok&&performance.now()-started<2500?"ONLINE":"LIMITED";}catch{return"LIMITED";}finally{clearTimeout(timer);}}
