type Stored={id:string;iv:number[];cipher:ArrayBuffer;expiresAt:string;consentGrantId?:string};
const DB="swasthyasetu-provider-secure";const STORE="care-packets";const KEYS="keys";
function open():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{request.result.createObjectStore(STORE,{keyPath:"id"});request.result.createObjectStore(KEYS);};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function key():Promise<CryptoKey>{const db=await open();const prior=await new Promise<CryptoKey|undefined>((resolve,reject)=>{const r=db.transaction(KEYS).objectStore(KEYS).get("device");r.onsuccess=()=>resolve(r.result as CryptoKey|undefined);r.onerror=()=>reject(r.error);});if(prior)return prior;const created=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);await new Promise<void>((resolve,reject)=>{const tx=db.transaction(KEYS,"readwrite");tx.objectStore(KEYS).put(created,"device");tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});return created;}
export async function cachePacket(packet:{packetId:string;expiresAt:string;consentGrantId?:string}):Promise<void>{if(!crypto.subtle||!indexedDB)throw new Error("Secure offline storage is unavailable.");const iv=crypto.getRandomValues(new Uint8Array(12));const bytes=new TextEncoder().encode(JSON.stringify(packet));const cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(),bytes);const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put({id:packet.packetId,iv:[...iv],cipher,expiresAt:packet.expiresAt,consentGrantId:packet.consentGrantId} satisfies Stored);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
async function remove(id:string):Promise<void>{const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
export async function cachedPackets():Promise<unknown[]>{const db=await open();const rows=await new Promise<Stored[]>((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result as Stored[]);r.onerror=()=>reject(r.error);});const output:unknown[]=[];for(const row of rows){if(Date.parse(row.expiresAt)<=Date.now()){await remove(row.id);continue;}try{const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(row.iv)},await key(),row.cipher);output.push(JSON.parse(new TextDecoder().decode(plain)) as unknown);}catch{await remove(row.id);}}return output;}
export async function purgePacketsOutsideGrants(activeGrantIds:string[]):Promise<void>{const allowed=new Set(activeGrantIds);const db=await open();const rows=await new Promise<Stored[]>((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).getAll();request.onsuccess=()=>resolve(request.result as Stored[]);request.onerror=()=>reject(request.error);});for(const row of rows)if(!row.consentGrantId||!allowed.has(row.consentGrantId))await remove(row.id);}
export async function purgeOffline():Promise<void>{const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction([STORE,KEYS],"readwrite");tx.objectStore(STORE).clear();tx.objectStore(KEYS).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
