import React,{useCallback,useState}from"react";
import{StyleSheet,Text,View}from"react-native";
import{useFocusEffect,useRouter}from"expo-router";
import{request}from"../../src/api/client.ts";
import{PATIENT_TOKEN_KEY}from"../../src/state/patientSession.ts";
import{cachePatientDiagnostics,pendingPatientOperations,readPatientDiagnostics,syncPatientOperations}from"../../src/connectivity/patient.ts";
import{Button}from"../../src/ui/Button.tsx";
import{Screen}from"../../src/ui/Screen.tsx";
import{ink,paper,radius,space,type}from"../../src/theme/tokens.ts";

interface Order{orderId:string;trackingCode:string;status:string;specimenStatus:string|null;consentStatus:string;scheduledAt:string|null;expectedBy:string|null;overdue:boolean;resultRecordId:string|null;destinationFacilityName?:string;test?:{display:string;kind:string}}
export default function PatientDiagnostics():React.ReactNode{
 const router=useRouter(),[orders,setOrders]=useState<Order[]>([]),[savedAt,setSavedAt]=useState<string|null>(null),[message,setMessage]=useState("Loading…"),[pending,setPending]=useState(pendingPatientOperations());
 const load=useCallback(async()=>{const result=await request<Order[]>("/patients/diagnostics/",{tokenKey:PATIENT_TOKEN_KEY});if(result.ok&&result.data){setOrders(result.data);setSavedAt(new Date().toISOString());await cachePatientDiagnostics(result.data);setMessage("Updated from the network.");}else{const cached=await readPatientDiagnostics<Order[]>();if(cached){setOrders(cached.value);setSavedAt(cached.savedAt);setMessage("Offline copy — status may be stale.");}else setMessage("No saved diagnostic status is available on this device.");}setPending(pendingPatientOperations());},[]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 async function retry(){const result=await syncPatientOperations();setPending(pendingPatientOperations());setMessage(`${result.sent} pending patient update(s) sent; ${result.rejected} need attention.`);await load();}
 return <Screen title="Diagnostics / निदान सेवाएँ"><View style={styles.notice}><Text style={styles.bold}>Operational tracking only</Text><Text style={styles.text}>Tests are selected and interpreted by clinicians. Evidence and turnaround times are not live service guarantees.</Text></View><Text style={styles.meta}>{message}{savedAt?` Saved ${new Date(savedAt).toLocaleString()}.`:""}</Text>{pending>0?<Button label={`Send ${pending} pending consent update(s)`}onPress={()=>void retry()}/>:null}{orders.length===0?<Text style={styles.text}>No diagnostic orders.</Text>:orders.map(order=><View style={styles.card}key={order.orderId}><Text style={styles.bold}>{order.test?.display??`Pending request ${order.trackingCode}`}</Text><Text style={styles.text}>{order.destinationFacilityName??"Receiving facility"}</Text><Text style={styles.text}>Order: {order.status.replaceAll("_"," ")}</Text>{order.specimenStatus?<Text style={styles.text}>Sample: {order.specimenStatus.replaceAll("_"," ")}</Text>:null}<Text style={styles.meta}>Consent: {order.consentStatus} · tracking code {order.trackingCode}</Text>{order.scheduledAt?<Text style={styles.meta}>Scheduled {new Date(order.scheduledAt).toLocaleString()}</Text>:null}{order.overdue?<Text style={styles.meta}>The promised operational timestamp has passed; contact the facility.</Text>:null}{order.resultRecordId?<Text style={styles.meta}>A report record is ready. Link its care context in My Health Record to share it with another hospital.</Text>:null}</View>)}<Button label="Refresh / ताज़ा करें"onPress={()=>void load()}/><Button label="Back"variant="secondary"onPress={()=>router.back()}/></Screen>;
}
const styles=StyleSheet.create({notice:{backgroundColor:paper.sunken,borderColor:paper.rule,borderWidth:1,borderRadius:radius.card,padding:space.md,gap:space.sm,marginBottom:space.md},card:{backgroundColor:paper.raised,borderColor:paper.rule,borderWidth:1,borderRadius:radius.card,padding:space.md,gap:space.sm,marginVertical:space.sm},bold:{...(type.body as object),fontWeight:"800",color:ink.strong},text:{...(type.body as object),color:ink.body},meta:{...(type.meta as object),color:ink.muted,marginBottom:space.sm}});
