import React,{useCallback,useState}from"react";import{Pressable,StyleSheet,Text,View}from"react-native";import{useFocusEffect,useRouter}from"expo-router";import{Screen}from"../../src/ui/Screen.tsx";import{Button}from"../../src/ui/Button.tsx";import{decideConsent,getAccessHistory,getContexts,getReferrals,getTimeline,linkContext,listConsents,revokeConsent,type AccessEvent,type CareContext,type ConsentItem,type Referral,type TimelineRecord}from"../../src/api/abdm.ts";import{queuePatientOperation,syncPatientOperations}from"../../src/connectivity/patient.ts";import{ink,paper,radius,space,type}from"../../src/theme/tokens.ts";
export default function Records():React.ReactNode{const router=useRouter();const[consents,setConsents]=useState<ConsentItem[]>([]);const[records,setRecords]=useState<TimelineRecord[]>([]);const[contexts,setContexts]=useState<CareContext[]>([]);const[audit,setAudit]=useState<AccessEvent[]>([]);const[referrals,setReferrals]=useState<Referral[]>([]);const[selected,setSelected]=useState<Record<string,string[]>>({});const[message,setMessage]=useState("Loading…");
 const load=useCallback(async()=>{const[c,r,x,a,f]=await Promise.all([listConsents(),getTimeline(),getContexts(),getAccessHistory(),getReferrals()]);if(c.ok&&c.data)setConsents(c.data);if(r.ok&&r.data)setRecords(r.data.records);if(x.ok&&x.data)setContexts(x.data);if(a.ok&&a.data)setAudit(a.data);if(f.ok&&f.data)setReferrals(f.data);setMessage([c,r,x,a,f].every(v=>v.ok)?"ABDM development mock—not NHA certified":"Some information could not be refreshed. Previously shown data may be stale.");},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
 function typesFor(c:ConsentItem){return selected[c.consentRequestId]??c.requestedHiTypes;}function toggle(c:ConsentItem,item:string){const current=typesFor(c);setSelected(v=>({...v,[c.consentRequestId]:current.includes(item)?current.filter(x=>x!==item):[...current,item]}));}
 async function decide(c:ConsentItem,decision:"APPROVE"|"DENY"){const types=typesFor(c);if(decision==="APPROVE"&&types.length===0){setMessage("Select at least one record type.");return;}const result=await decideConsent(c.consentRequestId,decision,decision==="APPROVE"?types:undefined);if(result.ok){setMessage(`Consent ${decision==="APPROVE"?"approved":"denied"}.`);await load();return;}queuePatientOperation("CONSENT_DECIDE",{consentRequestId:c.consentRequestId,decision,...(decision==="APPROVE"?{approvedHiTypes:types}:{})});setMessage("PENDING SYNC — this choice grants no provider access until the server accepts it.");}
 async function revoke(id:string){const result=await revokeConsent(id);if(result.ok){setMessage("Access revoked.");await load();return;}queuePatientOperation("CONSENT_REVOKE",{consentRequestId:id});setMessage("REVOCATION PENDING SYNC — cached provider access can be purged only after the server accepts this request.");}
 async function link(id:string){const result=await linkContext(id);if(result.ok){await load();return;}queuePatientOperation("CARE_CONTEXT_LINK",{careContextId:id});setMessage("Care-context link saved on this device and pending synchronization.");}
 async function retry(){const result=await syncPatientOperations();setMessage(`${result.sent} update(s) synchronized; ${result.rejected} need attention.`);await load();}
 return <Screen title="My health record / माझ्या आरोग्य नोंदी"><View style={styles.warning}><Text style={styles.bold}>Development mock only</Text><Text style={styles.text}>ABHA identifies you and manages consent. The card itself does not contain this medical history.</Text></View><Button label="Retry pending patient updates"variant="secondary"onPress={()=>void retry()}/><Text style={styles.section}>Consent requests / संमती विनंत्या</Text>{consents.length===0?<Text style={styles.text}>No consent requests.</Text>:consents.map(c=><View style={styles.card}key={c.consentRequestId}><Text style={styles.bold}>{c.requestingFacility.name}</Text><Text style={styles.text}>{c.requestingPractitioner.fullName} · {c.status}</Text><Text style={styles.meta}>{c.explanation.en}</Text>{c.status==="REQUESTED"?<><Text style={styles.meta}>Tap record types to include or exclude:</Text><View style={styles.chips}>{c.requestedHiTypes.map(item=><Pressable key={item}onPress={()=>toggle(c,item)}style={[styles.chip,typesFor(c).includes(item)&&styles.chipOn]}><Text style={typesFor(c).includes(item)?styles.chipTextOn:styles.chipText}>{item.replaceAll("_"," ")}</Text></Pressable>)}</View><Button label="Approve selected for 7-day episode"onPress={()=>void decide(c,"APPROVE")}/><Button label="Deny"variant="secondary"onPress={()=>void decide(c,"DENY")}/></>:c.status==="GRANTED"?<Button label="Revoke access now"variant="secondary"onPress={()=>void revoke(c.consentRequestId)}/>:null}<Text style={styles.meta}>Expires {new Date(c.validUntil).toLocaleString()}</Text></View>)}
 <Text style={styles.section}>Care contexts awaiting link</Text>{contexts.filter(c=>c.status==="PENDING").map(c=><View style={styles.card}key={c.careContextId}><Text style={styles.bold}>{c.display}</Text><Text style={styles.meta}>{c.facility.name}</Text><Button label="Link this care context"onPress={()=>void link(c.careContextId)}/></View>)}
 <Text style={styles.section}>Longitudinal timeline</Text>{records.length===0?<Text style={styles.text}>No linked records yet.</Text>:records.map(r=><View style={styles.card}key={r.recordId}><Text style={styles.tag}>{r.recordType.replaceAll("_"," ")}</Text><Text style={styles.bold}>{r.title}</Text><Text style={styles.text}>{r.sourceFacility.name} · {new Date(r.authoredAt).toLocaleDateString()}</Text><Text style={styles.meta}>{JSON.stringify(r.summary)}</Text></View>)}
 <Text style={styles.section}>Referral progress</Text>{referrals.length===0?<Text style={styles.text}>No referrals.</Text>:referrals.map(r=><View style={styles.card}key={r.referralId}><Text style={styles.bold}>{r.requestedService} · {r.status}</Text><Text style={styles.text}>{r.reason}</Text></View>)}
 <Text style={styles.section}>Who viewed my records</Text>{audit.length===0?<Text style={styles.text}>No provider access recorded.</Text>:audit.map(a=><View style={styles.card}key={a.accessEventId}><Text style={styles.bold}>{a.practitionerName} · {a.facilityName}</Text><Text style={styles.text}>{a.action.replaceAll("_"," ")} · {new Date(a.occurredAt).toLocaleString()}</Text><Text style={styles.meta}>{a.purpose}</Text></View>)}<Text style={styles.meta}>{message}</Text><Button label="Back"variant="secondary"onPress={()=>router.back()}/></Screen>}
const styles=StyleSheet.create({warning:{backgroundColor:"#FFF2CF",borderLeftColor:"#D9901A",borderLeftWidth:4,padding:space.md,marginBottom:space.lg},section:{...(type.section as object),color:ink.strong,marginTop:space.lg,marginBottom:space.sm},card:{backgroundColor:paper.raised,borderColor:paper.rule,borderWidth:1,borderRadius:radius.card,padding:space.md,gap:space.sm,marginBottom:space.md},bold:{...(type.body as object),fontWeight:"800",color:ink.strong},text:{...(type.body as object),color:ink.body},meta:{...(type.meta as object),color:ink.muted},tag:{...(type.meta as object),fontWeight:"800",color:"#9F4B2E"},chips:{flexDirection:"row",flexWrap:"wrap",gap:space.xs},chip:{borderWidth:1,borderColor:paper.rule,borderRadius:20,paddingHorizontal:space.sm,paddingVertical:space.xs},chipOn:{backgroundColor:"#175B4A",borderColor:"#175B4A"},chipText:{color:ink.body,fontSize:11},chipTextOn:{color:"white",fontSize:11}});
