import type { ProviderOperation,PatientOperation,OperationResult } from "@swasthyasetu/contracts/connectivity";
import { payloadFingerprint } from "@swasthyasetu/core";
import type { ProviderActor } from "../provider-auth/repo.ts";
import { publishRecord } from "../mock-abdm/service.ts";
import { createReferral,transitionReferral } from "../referrals/service.ts";
import * as diagnostic from "../diagnostics/service.ts";
import * as repo from "./repo.ts";
import { sha256 } from "../../util/hash.ts";

const fingerprint=(value:unknown)=>payloadFingerprint(value,sha256);
function sizeGuard(value:unknown):void{if(Buffer.byteLength(JSON.stringify(value),"utf8")>512*1024)throw Object.assign(new Error("Sync batch exceeds 512 KB."),{code:"23514"});}
function permanent(error:unknown):boolean{if(typeof error!=="object"||error===null)return false;const code="code"in error?String(error.code):"";return["23503","23505","23514","VALIDATION_FAILED","FORBIDDEN","NOT_FOUND","CONFLICT","VERSION_CONFLICT"].includes(code);}
function rejection(opId:string,error:unknown):OperationResult{return{operationId:opId,status:String((error as{code?:unknown})?.code)==="CONFLICT"?"CONFLICT":"REJECTED",message:error instanceof Error?error.message:"Operation rejected."};}
export async function pushProvider(actor:ProviderActor,operations:ProviderOperation[]):Promise<{results:OperationResult[];serverTime:string}>{sizeGuard(operations);const results:OperationResult[]=[];for(const op of operations){const payloadHash=fingerprint(op);try{const prior=await repo.findOperation(op.operationId,"PROVIDER",actor.provider_account_id);if(prior){if(prior.payload_hash!==payloadHash){results.push({operationId:op.operationId,status:"REJECTED",message:"Operation id reused with different data."});continue;}results.push({operationId:op.operationId,status:"DUPLICATE",serverId:typeof prior.result["serverId"]==="string"?prior.result["serverId"]:undefined});continue;}let serverId:string|undefined;let internallyRecorded=false;
 switch(op.opType){case"PROVIDER_RECORD_PUBLISH":serverId=(await publishRecord(actor,{operationId:op.operationId,...op.payload})).recordId;break;case"REFERRAL_CREATE":serverId=(await createReferral(actor,{operationId:op.operationId,...op.payload})).referralId;break;case"REFERRAL_TRANSITION":serverId=(await transitionReferral(actor,op.payload.referralId,{operationId:op.operationId,status:op.payload.status,scheduledAt:op.payload.scheduledAt,outcome:op.payload.outcome,followUp:op.payload.followUp})).referralId;break;case"DIAGNOSTIC_ORDER_CREATE":serverId=(await diagnostic.createOrder(actor,{operationId:op.operationId,...op.payload})).orderId;internallyRecorded=true;break;case"DIAGNOSTIC_ORDER_TRANSITION":serverId=(await diagnostic.transitionOrder(actor,op.payload.orderId,{operationId:op.operationId,status:op.payload.status,scheduledAt:op.payload.scheduledAt,note:op.payload.note})).orderId;internallyRecorded=true;break;case"DIAGNOSTIC_SPECIMEN_TRANSITION":serverId=(await diagnostic.transitionSpecimen(actor,op.payload.orderId,{operationId:op.operationId,status:op.payload.status,occurredAt:op.payload.occurredAt,note:op.payload.note})).orderId;internallyRecorded=true;break;case"DIAGNOSTIC_APPOINTMENT_TRANSITION":serverId=(await diagnostic.transitionAppointment(actor,op.payload.orderId,{operationId:op.operationId,status:op.payload.status,scheduledAt:op.payload.scheduledAt,note:op.payload.note})).orderId;internallyRecorded=true;break;case"DIAGNOSTIC_RESULT_PUBLISH":serverId=(await diagnostic.publishResult(actor,op.payload.orderId,{operationId:op.operationId,summary:op.payload.summary,fhirBundle:op.payload.fhirBundle})).orderId;internallyRecorded=true;break;case"DIAGNOSTIC_SERVICE_SIGNAL_CREATE":await diagnostic.addEvidence(actor,{operationId:op.operationId,...op.payload});serverId=op.payload.serviceId;break;}
 if(!internallyRecorded)await repo.recordProviderOperation({id:op.operationId,actorId:actor.provider_account_id,facilityId:actor.facility_id,type:op.opType,hash:payloadHash,result:{serverId}});results.push({operationId:op.operationId,status:"APPLIED",serverId});}catch(error){if(!permanent(error))throw error;results.push(rejection(op.operationId,error));}}return{results,serverTime:new Date().toISOString()};}
export async function pushPatient(patientId:string,operations:PatientOperation[]):Promise<{results:OperationResult[];serverTime:string}>{sizeGuard(operations);const results:OperationResult[]=[];for(const op of operations){try{const applied=await repo.applyPatientOperation({id:op.operationId,patientId,type:op.opType,hash:fingerprint(op),payload:op.payload});results.push({operationId:op.operationId,status:applied.duplicate?"DUPLICATE":"APPLIED",serverId:applied.serverId});}catch(error){if(!permanent(error))throw error;results.push(rejection(op.operationId,error));}}return{results,serverTime:new Date().toISOString()};}
