import { getDb } from "../db/client.ts";
import { api } from "../api/client.ts";

export interface DiagnosticReference { serviceId:string;districtCode:string;facilityName:string;evidenceText:string;test:{code:string;display:string;kind:string};turnaroundMinutesMin:number;turnaroundMinutesMax:number }
type EvidenceType="COLLECTION_CONFIRMED"|"PROCESSING_CONFIRMED"|"REAGENT_CONFIRMED"|"STOCK_OUT_REPORTED"|"MACHINE_DOWN_REPORTED"|"COLLECTION_PAUSED_REPORTED";
function uuid():string{return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const r=Math.floor(Math.random()*16),v=c==="x"?r:(r&3)|8;return v.toString(16);});}
function fingerprint(value:string):string{let hash=0x811c9dc5;for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,0x01000193);}return`fnv1a-${(hash>>>0).toString(16).padStart(8,"0")}`;}
export function listDiagnosticReference(district:string):DiagnosticReference[]{return getDb().getAllSync<{payload_json:string}>("SELECT payload_json FROM diagnostic_reference_cache WHERE district_code=? ORDER BY refreshed_at DESC",[district]).map(row=>JSON.parse(row.payload_json) as DiagnosticReference);}
export async function refreshDiagnosticReference(district:string):Promise<number>{const res=await api.get<{items:DiagnosticReference[];nextCursor:string|null}>(`/diagnostics/reference?districtCode=${encodeURIComponent(district)}&limit=500`);if(!res.ok||!res.data)return 0;const db=getDb(),at=new Date().toISOString();db.withTransactionSync(()=>{for(const item of res.data!.items)db.runSync("INSERT OR REPLACE INTO diagnostic_reference_cache(service_id,district_code,payload_json,refreshed_at) VALUES(?,?,?,?)",[item.serviceId,district,JSON.stringify(item),at]);});return res.data.items.length;}
export function queueDiagnosticSignal(serviceId:string,evidenceType:EvidenceType,note?:string):string{const id=uuid(),at=new Date().toISOString(),payload={serviceId,evidenceType,observedAt:at,...(note?{note}:{})},body=JSON.stringify(payload);getDb().runSync("INSERT INTO diagnostic_signal_outbox(operation_id,client_created_at,payload_json,payload_hash,next_attempt_at) VALUES(?,?,?,?,?)",[id,at,body,fingerprint(body),at]);return id;}
export function pendingDiagnosticSignals():number{return getDb().getFirstSync<{n:number}>("SELECT count(*) n FROM diagnostic_signal_outbox WHERE status='PENDING'")?.n??0;}
export async function syncDiagnosticSignals():Promise<number>{const db=getDb();const rows=db.getAllSync<{operation_id:string;payload_json:string;attempts:number}>("SELECT operation_id,payload_json,attempts FROM diagnostic_signal_outbox WHERE status='PENDING' AND next_attempt_at<=? ORDER BY client_created_at LIMIT 50",[new Date().toISOString()]);if(!rows.length)return 0;const res=await api.post<{results:Array<{operationId:string;status:string;message?:string}>}>("/diagnostics/signals/push",{operations:rows.map(row=>({operationId:row.operation_id,payload:JSON.parse(row.payload_json) as Record<string,unknown>}))});if(!res.ok||!res.data){for(const row of rows){const delay=Math.min(300_000,5_000*2**Math.min(row.attempts,6))+Math.floor(Math.random()*1000);db.runSync("UPDATE diagnostic_signal_outbox SET attempts=attempts+1,next_attempt_at=?,last_error=? WHERE operation_id=?",[new Date(Date.now()+delay).toISOString(),res.error?.message??"No acknowledgement",row.operation_id]);}return 0;}let sent=0;for(const item of res.data.results){if(item.status==="APPLIED"||item.status==="DUPLICATE"){db.runSync("DELETE FROM diagnostic_signal_outbox WHERE operation_id=?",[item.operationId]);sent++;}else db.runSync("UPDATE diagnostic_signal_outbox SET status='REJECTED',last_error=? WHERE operation_id=?",[item.message??item.status,item.operationId]);}return sent;}
