import { createHash } from "node:crypto";
import * as diagnostics from "@swasthyasetu/contracts/diagnostics";
import { badRequest, conflict, forbidden, notFound } from "../../plugins/errors.ts";
import type { ProviderActor } from "../provider-auth/repo.ts";
import * as repo from "./repo.ts";

const POSITIVE=new Set(["COLLECTION_CONFIRMED","PROCESSING_CONFIRMED","REAGENT_CONFIRMED"]);
const TERMINAL=new Set(["RESULT_READY","COMPLETED","DECLINED","CANCELLED"]);
const NEXT:Record<string,readonly string[]>={CREATED:["ACCEPTED","DECLINED","CANCELLED"],ACCEPTED:["SCHEDULED","IN_PROGRESS","DECLINED","CANCELLED"],SCHEDULED:["IN_PROGRESS","DECLINED","CANCELLED"],IN_PROGRESS:["RESULT_READY","CANCELLED"],RESULT_READY:["COMPLETED"]};
const SPECIMEN_NEXT:Record<string,readonly string[]>={COLLECTION_PENDING:["COLLECTED","REJECTED"],COLLECTED:["IN_TRANSIT","RECEIVED","REJECTED"],IN_TRANSIT:["RECEIVED","REJECTED"]};
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const iso=(value:Date|null)=>value?.toISOString()??null;
function evidence(row:repo.ServiceRow):string{if(!row.latest_evidence_at||!row.latest_evidence_type)return"No service activity report has been received.";const labels:Record<string,string>={COLLECTION_CONFIRMED:"collection activity",PROCESSING_CONFIRMED:"processing activity",REAGENT_CONFIRMED:"reagent confirmation",STOCK_OUT_REPORTED:"a stock-out",MACHINE_DOWN_REPORTED:"a machine-down event",COLLECTION_PAUSED_REPORTED:"collection paused"};const days=Math.max(0,Math.floor((Date.now()-row.latest_evidence_at.getTime())/86_400_000));return`${row.latest_reporter??"A facility worker"} reported ${labels[row.latest_evidence_type]??"service activity"} ${days} day${days===1?"":"s"} ago.`;}
function serviceView(row:repo.ServiceRow){return diagnostics.facilityDiagnosticService.parse({serviceId:row.service_id,test:{testId:row.test_id,codeSystem:row.code_system,code:row.code,display:row.display,kind:row.kind,specimenType:row.specimen_type,preparation:row.preparation},facilityId:row.facility_id,facilityName:row.facility_name,districtCode:row.district_code,latitude:row.latitude,longitude:row.longitude,phone:row.phone,collectionSupported:row.collection_supported,processingModel:row.processing_model,processingFacilityId:row.processing_facility_id,appointmentRequired:row.appointment_required,turnaroundMinutesMin:row.turnaround_minutes_min,turnaroundMinutesMax:row.turnaround_minutes_max,indicativeCostPaisaMin:row.indicative_cost_paisa_min,indicativeCostPaisaMax:row.indicative_cost_paisa_max,supportedSchemes:row.supported_schemes,lastPositiveAt:iso(row.last_positive_at),lastNegativeAt:iso(row.last_negative_at),evidenceText:evidence(row),...(row.distance_meters===undefined?{}:{distanceMeters:row.distance_meters})});}
function orderView(row:repo.OrderRow,clinical:boolean){const allowed=clinical&&row.can_view_clinical;return diagnostics.diagnosticOrderView.parse({orderId:row.order_id,trackingCode:row.tracking_code,...(allowed?{patientId:row.patient_id,test:{testId:row.test_id,codeSystem:row.code_system,code:row.code,display:row.display,kind:row.kind,specimenType:row.specimen_type,preparation:row.preparation},priority:row.priority,practitionerReason:row.practitioner_reason}:{}),originFacilityId:row.origin_facility_id,destinationFacilityId:row.destination_facility_id,destinationFacilityName:row.destination_facility_name,status:row.status,specimenStatus:row.specimen_status,consentStatus:row.consent_status,requestedWindowStart:iso(row.requested_window_start),requestedWindowEnd:iso(row.requested_window_end),scheduledAt:iso(row.scheduled_at),resultRecordId:row.result_record_id,expectedBy:iso(row.expected_by),overdue:row.expected_by!==null&&row.expected_by.getTime()<Date.now()&&!TERMINAL.has(row.status),createdAt:row.created_at.toISOString(),updatedAt:row.updated_at.toISOString()});}
export async function reference(input:ReturnType<typeof diagnostics.diagnosticReferenceQuery.parse>){let after:string|null=null;if(input.cursor){try{after=JSON.parse(Buffer.from(input.cursor,"base64url").toString("utf8"))["after"] as string;}catch{throw badRequest("Invalid diagnostic reference cursor.");}}const rows=await repo.referenceServices(input.districtCode,input.since??null,after,input.limit+1);const page=rows.slice(0,input.limit);const next=rows.length>input.limit?page.at(-1)?.service_id??null:null;return{items:page.map(serviceView),nextCursor:next?Buffer.from(JSON.stringify({after:next})).toString("base64url"):null,serverTime:new Date().toISOString()};}
export async function search(input:ReturnType<typeof diagnostics.diagnosticSearchQuery.parse>){return{items:(await repo.searchServices(input.code,input.districtCode,input.latitude,input.longitude)).map(serviceView),notice:"Directory evidence is time-stamped and is not a live service guarantee. Confirm before travel."};}
export async function configure(actor:ProviderActor,input:ReturnType<typeof diagnostics.configureServiceRequest.parse>){if(actor.role!=="FACILITY_ADMIN")throw forbidden("Only a facility administrator can configure diagnostic services.");return serviceView(await repo.configureService(actor.facility_id,input));}
export async function addEvidence(actor:ProviderActor,input:ReturnType<typeof diagnostics.createServiceEvidenceRequest.parse>){if(!["DOCTOR","LAB_TECH","FACILITY_ADMIN"].includes(actor.role))throw forbidden();const service=await repo.serviceById(input.serviceId);if(!service||service.facility_id!==actor.facility_id)throw notFound("Diagnostic service not found at this facility.");if(Date.parse(input.observedAt)>Date.now()+86_400_000)throw badRequest("observedAt is too far in the future.");const created=await repo.insertServiceEvidence({eventId:input.operationId,serviceId:input.serviceId,providerId:actor.practitioner_id,evidenceType:input.evidenceType,observedAt:input.observedAt,note:input.note});return{created,service:serviceView((await repo.serviceById(input.serviceId))!)};}
export async function addAshaEvidence(userId:string,district:string,input:ReturnType<typeof diagnostics.createServiceEvidenceRequest.parse>){const service=await repo.serviceById(input.serviceId);if(!service||service.district_code!==district)throw forbidden();if(Date.parse(input.observedAt)>Date.now()+86_400_000)throw badRequest("observedAt is too far in the future.");const created=await repo.insertServiceEvidence({eventId:input.operationId,serviceId:input.serviceId,workerId:userId,evidenceType:input.evidenceType,observedAt:input.observedAt,note:input.note});return{created,service:serviceView((await repo.serviceById(input.serviceId))!)};}
function tracking(operationId:string):string{const number=Number.parseInt(hash(operationId).slice(0,10),16)%10_000_000;return`D${number.toString().padStart(7,"0")}`;}
export async function createOrder(actor:ProviderActor,input:ReturnType<typeof diagnostics.createDiagnosticOrderRequest.parse>){if(actor.role!=="DOCTOR")throw forbidden("Only a doctor can create a diagnostic order.");const service=await repo.serviceById(input.serviceId);if(!service)throw notFound("Diagnostic service not found.");const row=await repo.createOrder({operationId:input.operationId,payloadHash:hash(input),accountId:actor.provider_account_id,practitionerId:actor.practitioner_id,originFacilityId:actor.facility_id,patientId:input.patientId,service,priority:input.priority,reason:input.practitionerReason,serviceRequest:input.serviceRequest,windowStart:input.requestedWindowStart,windowEnd:input.requestedWindowEnd,sharedTypes:input.sharedHiTypes,trackingCode:tracking(input.operationId)});return orderView(row,true);}
export async function listProviderOrders(actor:ProviderActor){const clinical=["DOCTOR","NURSE","LAB_TECH"].includes(actor.role);const rows=await repo.listOrders(actor.facility_id);for(const row of rows)if(clinical&&row.can_view_clinical)await repo.auditOrder({orderId:row.order_id,practitionerId:actor.practitioner_id,facilityId:actor.facility_id,action:"ORDER_LIST_READ"});return rows.map(row=>orderView(row,clinical));}
export async function getProviderOrder(actor:ProviderActor,id:string){const row=await repo.findOrder(id,actor.facility_id);if(!row)throw notFound("Diagnostic order not found.");const clinical=["DOCTOR","NURSE","LAB_TECH"].includes(actor.role);if(clinical&&row.can_view_clinical)await repo.auditOrder({orderId:id,practitionerId:actor.practitioner_id,facilityId:actor.facility_id,action:"ORDER_READ"});return orderView(row,clinical);}
export async function listPatientOrders(patientId:string){const rows=await repo.patientOrders(patientId);for(const row of rows)await repo.auditOrder({orderId:row.order_id,patientId,action:"PATIENT_ORDER_READ"});return rows.map(row=>orderView(row,true));}
export async function transitionOrder(actor:ProviderActor,id:string,input:ReturnType<typeof diagnostics.transitionDiagnosticOrderRequest.parse>){if(!["DOCTOR","NURSE","LAB_TECH"].includes(actor.role))throw forbidden();const row=await repo.findOrder(id,actor.facility_id);if(!row)throw notFound("Diagnostic order not found.");const destination=row.destination_facility_id===actor.facility_id,origin=row.origin_facility_id===actor.facility_id;if(input.status==="CANCELLED"&&!origin)throw forbidden("Only the ordering facility may cancel.");if(input.status!=="CANCELLED"&&!destination)throw forbidden("Only the destination facility may progress this order.");if(destination&&input.status!=="DECLINED"&&row.consent_status!=="GRANTED"&&row.origin_facility_id!==row.destination_facility_id){const grant=await repo.attachGrant(id,actor.facility_id);if(!grant)throw forbidden("Patient consent is required before this order can be opened.");row.consent_grant_id=grant;row.consent_status="GRANTED";row.can_view_clinical=true;}if(!(NEXT[row.status]??[]).includes(input.status))throw conflict(`Diagnostic order cannot move from ${row.status} to ${input.status}.`);if(input.status==="SCHEDULED"&&!input.scheduledAt)throw badRequest("A scheduled order needs a date and time.");const changed=await repo.transitionOrder({operationId:input.operationId,payloadHash:hash({id,...input}),accountId:actor.provider_account_id,practitionerId:actor.practitioner_id,facilityId:actor.facility_id,orderId:id,from:row.status,to:input.status,scheduledAt:input.scheduledAt,note:input.note});if(!changed)throw conflict("Diagnostic order changed before this update was applied.");return orderView(changed,true);}
export async function transitionAppointment(actor:ProviderActor,id:string,input:ReturnType<typeof diagnostics.transitionDiagnosticAppointmentRequest.parse>){if(!["DOCTOR","NURSE","LAB_TECH"].includes(actor.role))throw forbidden();const row=await repo.findOrder(id,actor.facility_id);if(!row||row.destination_facility_id!==actor.facility_id)throw notFound("Assigned diagnostic order not found.");if(row.consent_status!=="GRANTED"&&row.origin_facility_id!==row.destination_facility_id)throw forbidden("Patient consent is required.");return orderView(await repo.transitionAppointment({operationId:input.operationId,payloadHash:hash({id,...input}),accountId:actor.provider_account_id,practitionerId:actor.practitioner_id,facilityId:actor.facility_id,orderId:id,status:input.status,scheduledAt:input.scheduledAt,note:input.note}),true);}
export async function transitionSpecimen(actor:ProviderActor,id:string,input:ReturnType<typeof diagnostics.transitionSpecimenRequest.parse>){if(!["DOCTOR","NURSE","LAB_TECH"].includes(actor.role))throw forbidden();const row=await repo.findOrder(id,actor.facility_id);if(!row||row.destination_facility_id!==actor.facility_id)throw notFound("Assigned diagnostic order not found.");if(row.consent_status!=="GRANTED"&&row.origin_facility_id!==row.destination_facility_id)throw forbidden("Patient consent is required.");if(!row.specimen_status)throw badRequest("This diagnostic order has no specimen workflow.");if(!(SPECIMEN_NEXT[row.specimen_status]??[]).includes(input.status))throw conflict(`Specimen cannot move from ${row.specimen_status} to ${input.status}.`);if(input.status==="REJECTED"&&!input.note)throw badRequest("A rejected specimen needs a reason.");const changed=await repo.transitionSpecimen({operationId:input.operationId,payloadHash:hash({id,...input}),accountId:actor.provider_account_id,practitionerId:actor.practitioner_id,facilityId:actor.facility_id,orderId:id,from:row.specimen_status,to:input.status,occurredAt:input.occurredAt,note:input.note});if(!changed)throw conflict("Specimen changed before this update was applied.");return orderView(changed,true);}
export async function publishResult(actor:ProviderActor,id:string,input:ReturnType<typeof diagnostics.publishDiagnosticResultRequest.parse>){if(!["DOCTOR","LAB_TECH"].includes(actor.role))throw forbidden("Only an assigned doctor or laboratory technician can publish a diagnostic result.");const order=await repo.findOrder(id,actor.facility_id);if(!order||order.destination_facility_id!==actor.facility_id)throw notFound("Assigned diagnostic order not found.");if(order.consent_status!=="GRANTED"&&order.origin_facility_id!==order.destination_facility_id)throw forbidden("Patient consent is required.");if(!["ACCEPTED","SCHEDULED","IN_PROGRESS"].includes(order.status))throw conflict("The order is not ready for result publication.");const types=input.fhirBundle.entry.map(entry=>entry.resource["resourceType"]);if(!types.includes("Composition")||!types.includes("ServiceRequest")||!types.includes("DiagnosticReport")||!types.includes("Observation"))throw badRequest("The result bundle must contain Composition, ServiceRequest, DiagnosticReport and Observation resources.");if(order.kind==="LAB"&&!types.includes("Specimen"))throw badRequest("A laboratory result bundle must contain its Specimen resource.");const profile=input.fhirBundle.meta.profile;if(!profile.includes("https://nrces.in/ndhm/fhir/r4/StructureDefinition/DocumentBundle"))throw badRequest("FHIR Bundle must declare the ABDM DocumentBundle profile.");const changed=await repo.publishResult({operationId:input.operationId,payloadHash:hash({id,...input}),accountId:actor.provider_account_id,practitionerId:actor.practitioner_id,facilityId:actor.facility_id,order,summary:input.summary,bundle:input.fhirBundle,checksum:hash({orderId:id,bundle:input.fhirBundle})});return orderView(changed,true);}
