/**
 * FILE: packages/core/src/facilities/types.ts
 * PLAN: IMPLEMENTATION_PLAN.md §6.6–6.8
 * STATUS: COMPLETE — do not modify
 *
 * Shared vocabulary of the routing engine.
 */

import type { UrgencyTier } from "../triage/types.ts";

// ---------------------------------------------------------------- capability

export type CapabilityLevel = 1 | 2 | 3 | 4 | 5;

/**
 * What a facility must be able to do before it may be recommended.
 * Applied as a HARD FILTER before any scoring — distance never selects a
 * facility on its own.
 */
export interface CapabilityRequirement {
  minLevel: CapabilityLevel;
  requiredTags: string[];
}

// ---------------------------------------------------------------- freshness

/**
 * How much the system trusts that a facility is currently functioning.
 * This is EVIDENCE AGE, not live availability — the system has no live feed.
 */
export type FreshnessBand =
  | "FRESH"
  | "AGING"
  | "STALE"
  | "REPORTED_CLOSED"
  | "UNKNOWN";

export interface FreshnessConfig {
  /** Exponential decay constant in days. Default 14. */
  tauDays: number;
  /** Confirmed within this many days → FRESH. Default 3. */
  freshWithinDays: number;
  /** Confirmed within this many days → AGING, beyond → STALE. Default 14. */
  agingWithinDays: number;
  /** A negative signal this recent outranks an older confirmation. Default 7. */
  negativeWindowDays: number;
  /** Confidence multiplier when REPORTED_CLOSED. Default 0.25. */
  negativeMultiplier: number;
}

export interface FreshnessAssessment {
  band: FreshnessBand;
  /** 0..1. Feeds the ranking score directly. */
  confidence: number;
  /** Whole days since last confirmation; null when never confirmed. */
  ageDays: number | null;
  /**
   * GUARDRAIL: user-facing copy. Never contains "open", "available" or
   * "running" — it states evidence and its age, and the reader draws the
   * conclusion.
   */
  copy: string;
}

// ---------------------------------------------------------------- ranking

export interface FacilityCandidate {
  facilityId: string;
  name: string;
  facilityType: string;
  capabilityLevel: CapabilityLevel;
  capabilityTags: string[];
  travelSeconds: number;
  distanceMeters: number;
  /** 'ESTIMATED' must be surfaced to the user as an estimate, not a road route. */
  travelSource: "OSRM" | "ESTIMATED";
  lastConfirmedAt: string | null;
  lastNegativeAt: string | null;
  latitude: number;
  longitude: number;
  phone: string | null;
}

export interface RankedFacility {
  facility: FacilityCandidate;
  score: number;
  breakdown: { capability: number; time: number; freshness: number };
  freshness: FreshnessAssessment;
  travelEstimated: boolean;
  /** Deterministic template strings. NEVER generated by a language model. */
  reasons: string[];
  /** 1-based position after sorting. */
  rank: number;
}

export interface RankingOutcome {
  results: RankedFacility[];
  /** True when requirements had to be relaxed to return anything at all. */
  fallbackApplied: boolean;
  /** Capability tags dropped to find a result. The UI must state these plainly. */
  unmetRequirements: string[];
  requirement: CapabilityRequirement;
}

export interface RankingConfig {
  weights: Record<UrgencyTier, { capability: number; time: number; freshness: number }>;
  /** Travel minutes past which timeScore is 0, per tier. */
  horizonMinutes: Record<UrgencyTier, number>;
  freshness: FreshnessConfig;
  maxResults: number;
  /** Order in which requiredTags are dropped during fallback. Clinical tags last. */
  tagDropOrder: string[];
  /** Never relax an EMERGENCY below this level. Default 2. */
  minEmergencyLevel: CapabilityLevel;
}
