export const MARATHI_QUESTIONS: Readonly<Record<string, string>> = {
  PRIMARY_CONCERN: "सध्या सर्वात मोठा त्रास कोणता आहे?",
  IMMEDIATE_DANGER_SIGNS: "यापैकी सध्या काय होत आहे? लागू असलेले सर्व पर्याय निवडा.",
  DRINKING: "रुग्ण पाणी, दूध किंवा अन्न कसे घेत आहे?",
  CONTEXT_DANGER_SIGNS: "यापैकी काय लागू होते?",
  BODY_REGION: "शरीराच्या कोणत्या भागात त्रास आहे?",
  BODY_SIDE: "त्रास कोणत्या बाजूला आहे?",
  BODY_SUBREGION: "त्या भागात त्रास सर्वात जास्त कुठे आहे?",
  LOCAL_SYMPTOM_TYPE: "त्या ठिकाणी काय जाणवत आहे?",
  ONSET_PATTERN: "त्रास कसा सुरू झाला?",
  DURATION_ENTRY: "हा त्रास किती काळापासून आहे?",
  ASSOCIATED_AND_PROGRESSION: "आणखी काय होत आहे? लागू असलेले सर्व पर्याय निवडा.",
  ACTIVITY: "या त्रासाचा रोजच्या कामांवर किती परिणाम होत आहे?",
  TRIGGER_AND_CONTEXT: "त्रास सुरू होण्यापूर्वी काय झाले होते?",
  FINAL_LOCATION_MODE: "शेवटी, त्रास सर्वात जास्त कुठे जाणवतो?",
};

export const MARATHI_OPTIONS: Readonly<Record<string, string>> = {
  not_sure: "माहीत नाही", none: "यापैकी काहीही नाही",
  head_face: "डोके किंवा चेहरा", neck_throat: "मान किंवा घसा", chest: "छाती",
  abdomen_pelvis: "पोट किंवा ओटीपोट", back: "पाठ", arm_hand: "बाहू किंवा हात",
  leg_foot: "पाय", skin: "त्वचा", all_over: "संपूर्ण शरीरात", multiple: "एकापेक्षा जास्त ठिकाणी",
  forehead: "कपाळ", eye: "डोळा", ear: "कान", nose: "नाक", mouth_jaw: "तोंड किंवा जबडा",
  back_of_head: "डोक्याचा मागचा भाग", whole_head: "संपूर्ण डोके",
  front_neck: "मानेचा पुढचा भाग", back_neck: "मानेचा मागचा भाग", throat: "घसा",
  centre_chest: "छातीचा मध्यभाग", upper_chest: "छातीचा वरचा भाग", lower_chest: "छातीचा खालचा भाग", ribs: "बरगड्यांजवळ",
  upper_abdomen: "पोटाचा वरचा भाग", lower_abdomen: "पोटाचा खालचा भाग", around_navel: "नाभीजवळ", pelvis_groin: "ओटीपोट किंवा जांघेचा सांधा",
  upper_back: "पाठीचा वरचा भाग", middle_back: "पाठीचा मध्यभाग", lower_back: "कंबर",
  shoulder: "खांदा", upper_arm: "वरचा बाहू", elbow: "कोपर", forearm: "खालचा बाहू", wrist_hand: "मनगट किंवा हात", finger: "बोट",
  hip: "नितंब", thigh: "मांडी", knee: "गुडघा", calf: "पोटरी", ankle: "घोटा", foot_toe: "पाऊल किंवा पायाचे बोट",
  one_patch: "एका ठिकाणी", several_patches: "अनेक ठिकाणी", widespread_skin: "त्वचेवर अनेक ठिकाणी",
  whole_body: "संपूर्ण शरीर", several_areas: "अनेक भाग",
  pain: "वेदना", fever: "ताप", breathing_fast: "श्वास वेगाने चालणे किंवा श्वास घेण्यास त्रास", cough: "खोकला",
  weak_dizzy: "अशक्तपणा किंवा चक्कर", digestive: "पोट, जुलाब किंवा उलटीचा त्रास", urinary: "लघवीचा त्रास",
  rash_skin: "पुरळ किंवा त्वचेचा त्रास", injury: "दुखापत", heavy_bleeding: "खूप रक्तस्राव होत आहे आणि थांबत नाही",
  pregnancy: "गर्भावस्थेशी संबंधित काळजी", other: "इतर",
  unconscious: "रुग्ण जागा होत नाही", convulsion: "शरीराला झटके येणे", chest_pain: "छातीत वेदना",
  one_side_weak: "एका बाजूला अचानक अशक्तपणा", speech_difficulty: "अचानक बोलण्यास त्रास",
  normally: "नेहमीप्रमाणे", poorly: "नेहमीपेक्षा कमी", unable: "अजिबात पिऊ शकत नाही",
  infant_fever: "दोन महिन्यांपेक्षा लहान बाळाला ताप आहे", not_feeding: "मूल दूध किंवा अन्न घेत नाही",
  blood_in_stool: "शौचात रक्त आहे", vomits_everything: "खाल्लेले किंवा प्यायलेले सर्व उलटून जाते",
  severe_headache: "डोक्यात खूप तीव्र वेदना आहेत", blurred_vision: "धूसर दिसत आहे",
  face_hands_swelling: "चेहरा किंवा हातांवर सूज आहे", reduced_fetal_movement: "गर्भातील बाळाची हालचाल कमी आहे",
  left: "डाव्या बाजूला", right: "उजव्या बाजूला", both: "दोन्ही बाजूंना", middle: "मध्यभागी",
  widespread: "अनेक ठिकाणी किंवा संपूर्ण भागात", not_applicable: "हे लागू होत नाही",
  swelling: "सूज", burning: "जळजळ", burning_urination: "लघवी करताना जळजळ", itching: "खाज",
  numbness: "बधिरपणा", weakness: "अशक्तपणा", movement_difficulty: "हालचाल करण्यास त्रास", rash: "पुरळ किंवा चट्टे",
  sudden: "अचानक", gradual: "हळूहळू", after_event: "एखादी घटना किंवा काम झाल्यानंतर",
  getting_worse: "त्रास वाढत आहे", spreading: "दुसऱ्या भागात पसरत आहे", vomiting: "उलटी", diarrhoea: "पातळ जुलाब", dizziness: "चक्कर",
  normal: "काहीही परिणाम नाही", less_active: "नेहमीपेक्षा कमी काम करता येते", basic_activities_impossible: "चालणे किंवा आवश्यक काम करणे शक्य नाही",
  physical_work: "जड किंवा शारीरिक काम", eating: "खाल्ल्यानंतर", insect_bite: "कीटक चावला",
  medicine: "औषध घेतल्यानंतर", chronic_illness: "दीर्घकाळाची आरोग्य समस्या आहे",
  confirmed: "वर निवडलेले ठिकाण", cannot_locate: "एक ठराविक ठिकाण सांगता येत नाही",
};

export const MARATHI_SIDE_LABELS: Readonly<Record<string, string>> = {
  left: "डावीकडे", right: "उजवीकडे", both: "दोन्ही बाजूंना", middle: "मध्यभागी", widespread: "अनेक ठिकाणी",
};
